#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/75e344d4-3ed3-48d2-9142-2cb641e91164/ # 
title: Product


traits:
  mycollection:
    responses:
               
      400:
        body:
          application/json:
            example:
              
              
 
resourceTypes:
  collection:
    usage: This API is used by <<resourcePathName>>
    description: API is used to retrieve and create the productes about <<resourcePathName>>
    get:
      responses:
        200:
          body:
            application/json:
              example:
      
    put:
      description: This API is used to update products about <<resourcePathName>>
      responses:
        201:
          body:
            application/json:
              example: !include example.json 
    delete:
      description: This API is used to delete products about <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              example:
        
  
/product:
  get:
      description: This API used to retrieve all product details about <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              example:
      is:
        mycollection
                    
  post:
      description: This API used to creat the roduct details about <<resourcePathName>>
      responses:
        201:
          body:
            application/json:
              example:   
      is:
       mycollection:
                           
 
              
  /{productID}:
    type:
      collection
    is:
      mycollection:
                        
                    
/Bills:
  get:
      description: This API used to retrieve all product details about <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              example:
      is:
        mycollection:
                  
  post:
      description: This API used to creat the roduct details about <<resourcePathName>>
      responses:
        201:
          body:
            application/json:
              example:
      is:
        mycollection:
                   

  /{BillsID}:
    type:
      collection:
    is:
      mycollection:
        
  
  
/ProductCatagory:
  get:
      description: This API used to retrieve all product details about <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              example:

      is:
        mycollection:
                  
  post:
      description: This API used to creat the roduct details about <<resourcePathName>>
      responses:
        201:
          body:
            application/json:
              example:
      is:
        mycollection:
                   
            
  /{ProductCatagoryID}:
     type:
        collection:
     is:
      mycollection:
          
           
 